# Generated by Django 3.1.1 on 2020-09-13 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_create_sms_app_initial_migrations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phonebook',
            old_name='phone_numnber',
            new_name='phone_number',
        ),
    ]
